// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedLinkDashboard.Models;

public partial class Doctor
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Password { get; set; }

    public int SpecialityId { get; set; }

    public string About { get; set; }

    public double? Rate { get; set; }

    public string ProfilePic { get; set; }

    public virtual Speciality Speciality { get; set; }
}