// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedLinkDashboard.Models;

public partial class Patient
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateOnly BirthDate { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Password { get; set; }

    public string ProfilePic { get; set; }
}