// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedLinkDashboard.Models;

public partial class Product
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public decimal Price { get; set; }
}